version: "3.9"
services:
  postgres-user-service:
    image: postgres:13.3
    networks:
      - internal
    container_name: postgres-user-service
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME:-app}
      POSTGRES_USER: ${USER_SERVICE_DB_USER:?error}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD:?error}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/user-service-db:/var/lib/postgresql/data

  user-service:
    build: ./services/user-service
    container_name: user-service
    networks:
      - internal
    environment:
      POSTGRES_DB_NAME: ${USER_SERVICE_DB_NAME:-app}
      POSTGRES_DB_USER: ${USER_SERVICE_DB_USER:?error}
      POSTGRES_DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD:?error}
      POSTGRES_DB_HOST: ${USER_SERVICE_DB_HOST:-postgres-user-service}
      POSTGRES_DB_PORT: ${USER_SERVICE_DB_PORT:-5432}
    depends_on:
      - postgres-user-service


  postgres-store-service:
    image: postgres:13.3
    networks:
      - internal
    container_name: postgres-store-service
    environment:
      POSTGRES_DB: ${STORE_SERVICE_DB_NAME:-app}
      POSTGRES_USER: ${STORE_SERVICE_DB_USER:?error}
      POSTGRES_PASSWORD: ${STORE_SERVICE_DB_PASSWORD:?error}
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/store-service-db:/var/lib/postgresql/data

  store-service:
    build: ./services/store-service
    container_name: store-service
    networks:
      - internal
    environment:
      POSTGRES_DB_NAME: ${STORE_SERVICE_DB_NAME:-app}
      POSTGRES_DB_USER: ${STORE_SERVICE_DB_USER:?error}
      POSTGRES_DB_PASSWORD: ${STORE_SERVICE_DB_PASSWORD:?error}
      POSTGRES_DB_HOST: ${STORE_SERVICE_DB_HOST:-postgres-store-service}
      POSTGRES_DB_PORT: ${STORE_SERVICE_DB_PORT:-5432}
    depends_on:
      - postgres-store-service

networks:
  internal:
    driver: bridge
