spring:
    application:
        name: product-service
    datasource:
        username: ${POSTGRES_DB_USER}
        password: ${POSTGRES_DB_PASSWORD}
        url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:app}
    liquibase:
        enabled: true
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                hbm2ddl:
                    auto: none
        hibernate:
            ddl-auto: validate