spring:
    application:
        name: product-service
    kafka:
        bootstrap-servers: ${KAFKA_SERVERS}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    datasource:
        username: ${POSTGRES_DB_USER}
        password: ${POSTGRES_DB_PASSWORD}
        url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:app}
        driver-class-name: org.postgresql.Driver
    liquibase:
        enabled: true
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                hbm2ddl:
                    auto: none
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate


logging:
    level:
        root: info

server:
    tomcat:
        relaxed-query-chars:
            - '{'
            - '}'
            - '['
            - ']'
    port: 8080

springdoc:
    api-docs:
        path: /api-docs