spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    username: order-service
    password: order-service
    url: jdbc:postgresql://localhost:5432/app
  liquibase:
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
    hibernate:
      ddl-auto: validate